name: test
on: push

jobs:
  build:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
      - run: bun run build

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          tar -czvf git-buddy.tar.gz build/git-buddy

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: build/git-buddy
          GHR_DELETE: true
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
