name: publish

# This will trigger a publish when a tag is pushed
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun checks
      - run: bun run build
      - run: chmod +x build/git-buddy
      - run: bun scripts/notes.ts ${{ github.ref_name }} release-notes.md

      - name: Release
        uses: fnkr/github-action-ghr@ghr-options
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./build
          GHR_DELETE: true
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_BODY_FILE: ../release-notes.md
