name: test
on:
  push:
    tags:
      - "*"

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
      - run: bun run build

      - uses: Shopify/upload-to-release@v1
        with:
          name: my-artifact
          path: build/index.js
          repo-token: ${{ secrets.GITHUB_TOKEN }}
